# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the USB input drivers
#

ccflags-$(CONFIG_USB_HID_COMPOSITE_DEBUG)			+= -DDEBUG -Og
obj-$(CONFIG_USB_HID_COMPOSITE)						+= hid-composite.o
obj-$(CONFIG_USB_HID_COMPOSITE_POWER_SUPPLY)		+= hid-composite.o hid-power-supply.o
obj-$(CONFIG_USB_HID_COMPOSITE_RTC)					+= hid-composite.o hid-rtc.o
obj-$(CONFIG_USB_HID_COMPOSITE_RGB_LEDS)			+= hid-composite.o hid-led.o
obj-$(CONFIG_USB_HID_COMPOSITE_TYPEC)			    += hid-composite.o hid-typec.o
obj-$(CONFIG_USB_HID_COMPOSITE_GPIO)				+= hid-composite.o hid-gpio.o

obj-$(CONFIG_USB_HID_COMPOSITE_ALL)					+= hid-composite.o hid-gpio.o hid-typec.o hid-led.o hid-rtc.o hid-power-supply.o